#docker run -e URL="jdbc:postgresql://192.168.64.1:5432/software" -p 8008:8008 demo:2.0.0
#docker run -d --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword
# -v /Users/jrojas/Desktop/postgres:/var/lib/postgresql/data -p 5432:5432 \ postgres
version: "2.4"



services:
  postgres:
    image: postgres:15
    mem_limit: 1024m
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /Users/jrojas/Desktop/postgres-arqui-2:/var/lib/postgresql/data
#  currency-converter:
#    image: demo:3.0.1
#    restart: always
#    ports:
#      - "8008:8008"
#    environment:
#      URL: "${POSTGRES_URL}"
#      API_KEY: "${API_KEY}"
#      TEST: "${TEST}"
#    depends_on:
#      - postgres
#  angular:
#    image: angular-software:0.2.0-docker
#    ports:
#      - "4200:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf